### ISSUE TITLE
Could you please upload config file to the model dmis-lab/phrase-reranker-multi

### ISSUE THREAD

**Issue by YanJiangJerry** [dmis-lab/TouR#3]
Hi, I find there are no model files in dmis-lab/phrase-reranker-multi and the code in this repertory relies on the reranker model , could you upload the config file, please?

**Comment by mjeensung** [comment]
Hi @YanJiangJerry 

Thank you for reporting the issue!

We have uploaded phrase re-ranker checkpoints, which can be found at the following link:
https://github.com/dmis-lab/TouR#model-list

Additionally, we have provided scripts for training the re-rankers for your reference:
https://github.com/dmis-lab/TouR/tree/main/cross_encoder

If you have any further questions, please don't hesitate to ask.
